version: '2'

services:
  dump1090:
    restart: always
    build: ./dump1090
    expose:
      - "8080"
    privileged: true
    command: --net --interactive
    logging:
      driver: "none"

  poster:
    restart: always
    build: ./poster
    env_file: .env
    command: python post_data.py
    volumes:
      - ./poster:/usr/src/app/
    links:
      - dump1090:dump1090
    logging:
      driver: "none"
