dump1090:
  restart: always
  build: ./dump1090
  expose:
    - "8080"
  privileged: true
  command: --net

poster:
  restart: always
  build: ./poster
  env_file: .env
  command: python post_data.py
  links:
  - dump1090:dump1090

